# Generated by Django 2.1.5 on 2025-03-14 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('apellido', models.CharField(max_length=200)),
                ('tipoSangre', models.CharField(max_length=200)),
                ('alergias', models.CharField(max_length=200)),
                ('condicionesMedicas', models.CharField(max_length=200)),
                ('fechaNacimiento', models.DateField()),
            ],
        ),
    ]
