# Generated by Django 2.1.5 on 2025-03-14 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('paciente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoMedico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaEvento', models.DateField()),
                ('descripcion', models.CharField(max_length=255)),
                ('tipoEvento', models.IntegerField(choices=[(1, 'Consulta Médica'), (2, 'Cirugía'), (3, 'Prescripción de Medicamento'), (4, 'Examen')], default=1)),
                ('paciente', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='paciente.Paciente')),
            ],
        ),
    ]
